version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
