version: '3'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - '5000:5000'
        volumes:
            - /app/node_modules
            - .:/app
